---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-console
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-console
  namespace: openshift-console
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: openshift-console
    namespace: openshift-console
